### ISSUE TITLE
SRT -> KSR: home_srtdiagram.png graphic on front page needs updating

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/ksr-app#23]
the graphic on the front page under "How can data help put an end to systemic racism?" (`home_srtdiagram.png`) needs to have its text updated to switch from the old SRT branding to the new KSR branding.

![Screen Shot 2022-02-23 at 9 10 07 AM](https://user-images.githubusercontent.com/7741604/155377914-5b911c2b-d6aa-4ad8-96f0-925f7058bcf6.png)

**Comment by peetucket** [comment]
Fixed by #25
